# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!

target ‘Book’ do

pod 'AFNetworking'
pod 'MJRefresh'
pod 'FMDB'
pod 'SnapKit'
pod 'Toast'
pod 'MBProgressHUD'
pod 'SDWebImage'
pod 'UITableView+FDTemplateLayoutCell'

end

